Custom JWT Token Issuer Sample
wso2/samples-is pull request #269
Opened 2020-11-27 05:39 UTC by RajeshTammali

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2020-11-27 05:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/samples-is?pullRequest=269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/samples-is?pullRequest=269) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/samples-is?pullRequest=269) it.</sub>

2020-11-27 05:42 UTC, mefarazath commented on oauth2/custom-token-issuer/src/README.MD
> +Copy the jar from target folder into  $IS_HOME/repository/components/lib-location
```suggestion
Copy the jar from target folder into  $IS_HOME/repository/components/lib location

```

2020-11-27 05:47 UTC, mefarazath commented on oauth2/pom.xml
> +</project>
```suggestion
</project>

```

2020-11-27 05:47 UTC, mefarazath commented on oauth2/custom-token-issuer/src/main/java/org/wso2/carbon/identity/extensions/CustomJWTTokenIssuer.java
> +}
```suggestion
}

```

2020-11-27 05:47 UTC, mefarazath commented on oauth2/custom-token-issuer/src/README.MD
> +
Remove unnecessary new lines

2020-11-27 12:51 UTC, piraveena requested changes

2020-11-27 12:51 UTC, piraveena commented on oauth2/custom-token-issuer/src/README.MD
> +
remove new line

2020-11-27 12:51 UTC, piraveena commented on oauth2/custom-token-issuer/src/main/java/org/wso2/carbon/identity/extensions/CustomJWTTokenIssuer.java
> +
remove new line.

2020-11-27 12:51 UTC, piraveena commented on oauth2/custom-token-issuer/src/main/java/org/wso2/carbon/identity/extensions/CustomJWTTokenIssuer.java
> +	public CustomJWTTokenIssuer() throws IdentityOAuth2Exception {
new line should be there after the method signature. Apply wso2 code style https://sites.google.com/a/wso2.com/engineering/Home/masteringintellijidea

2020-11-27 12:51 UTC, piraveena commented on oauth2/custom-token-issuer/src/main/java/org/wso2/carbon/identity/extensions/CustomJWTTokenIssuer.java
> +
remove new line

2021-02-16 05:56 UTC, isharak commented
@RajeshTammali 
Since our policy is not to keep PR open for a long time I'll close this PR.
Can you please address the change requests and resend the PR again.

Thanks.

2021-04-05 09:15 UTC, mefarazath commented
Improved PR added with https://github.com/wso2/samples-is/pull/275

2021-04-05 09:15 UTC, closed without merging